os: linux
dist: trusty

env:
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/bianchi_modular_forms/test_bmf.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/abvar/fq/test_av.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/abvar/fq/test_browse_page.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/galois_groups/test_galoisgroup.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/siegel_modular_forms/test_siegel_modular_forms.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/genus2_curves/test_genus2_curves.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/lfunctions/test_lfunctions.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/lfunctions/test_lfunction_degree_2.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/sato_tate_groups/test_st.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/hilbert_modular_forms/test_hmf.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/belyi/test_belyi.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_utils.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_spelling.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_template_namespace.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_acknowlegments.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_homepage.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_tensor_products.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_dynamic_knowls.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/tests/test_root.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/hecke_algebras/test_hecke_algebras.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/elliptic_curves/test_ell_curves.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/elliptic_curves/test_browse_page.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/lattice/test_lattice.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/modular_forms/maass_forms/maass_waveforms/test_mwf.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/knowledge/test_knowls.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/local_fields/test_localfields.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/users/test_users.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/artin_representations/test_artin_representation.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/classical_modular_forms/test_cmf.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/ecnf/test_ecnf.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/ecnf/test_isog_class.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/api/test_api.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/characters/test_characters.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/number_fields/test_numberfield.py
  - SAGE_VERSION=8.8 TESTFILE=lmfdb/higher_genus_w_automorphisms/test_hgcwa.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/bianchi_modular_forms/test_bmf.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/abvar/fq/test_av.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/abvar/fq/test_browse_page.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/galois_groups/test_galoisgroup.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/siegel_modular_forms/test_siegel_modular_forms.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/genus2_curves/test_genus2_curves.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/lfunctions/test_lfunctions.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/lfunctions/test_lfunction_degree_2.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/sato_tate_groups/test_st.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/hilbert_modular_forms/test_hmf.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/belyi/test_belyi.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_utils.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_spelling.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_template_namespace.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_acknowlegments.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_homepage.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_tensor_products.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_dynamic_knowls.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/tests/test_root.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/hecke_algebras/test_hecke_algebras.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/elliptic_curves/test_ell_curves.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/elliptic_curves/test_browse_page.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/lattice/test_lattice.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/modular_forms/maass_forms/maass_waveforms/test_mwf.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/knowledge/test_knowls.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/local_fields/test_localfields.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/users/test_users.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/artin_representations/test_artin_representation.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/classical_modular_forms/test_cmf.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/ecnf/test_ecnf.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/ecnf/test_isog_class.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/api/test_api.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/characters/test_characters.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/number_fields/test_numberfield.py
  - SAGE_VERSION=9.1beta9 TESTFILE=lmfdb/higher_genus_w_automorphisms/test_hgcwa.py

# blocklist
branches:
  except:
  - web
  - dev

addons:
    apt:
        packages:
            # needed for sage
            - binutils
            - gcc
            - g++
            - gfortran
            - make
            - perl
            - tar
            - git
            - openssl
            - libssl-dev
            # needed for pyflakes
            - python3-pip
            # needed for coveralls
            - python-pip
            # to run nosetests in parallel
            - parallel


install:
    # assert parallel
    - parallel --version
    # install the latest pyflakes
    - pip3 install pyflakes --user
    # install a version of pylint having --py3k
    - pip2 install pylint --user
    # install the latest coveralls
    - pip install coveralls --user
    - export PATH=${HOME}/.local/bin/:${PATH}

    # install SAGE with GAP already built in
    # see: https://github.com/edgarcosta/binary-pkg
    # - export SAGE_VERSION=8.8 # this is now set in env above
    - echo $SAGE_VERSION
    - export SAGE_DIR=${HOME}/SageMath
    - export SAGE="${SAGE_DIR}/sage"
    - export SAGE_INSTALL_GCC=no
    - export MAKE='make -j4'
    # what is the load on the server
    - uptime
      #- wget  --no-verbose http://grace.mit.edu/sage-lmfdb/sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2
    - wget  --no-verbose https://math.mit.edu/~edgarc/sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2
    # what is the load on the server
    - uptime
    # travis_wait extends the default 10 minute timeout to 40 minutes
    - travis_wait 40 time tar xf sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2 -C ${HOME}

    # trigger the patch once script
    - ${SAGE} --version > patch_once_log
    # assert that we have GAP
    - ${SAGE} -python -c 'from sage.all import gap;G = gap.TransitiveGroup(9, 2); print(G)'
    # install LMFDB requirements
    - ${SAGE} -pip install -r requirements.txt

before_script:
    # assert that devmirror.lmfdb.xyz accepts our connections
    - nc -vz  devmirror.lmfdb.xyz 5432
    # how much free ram do we have
    - free -m
    # what is the load on the server
    - uptime

script:
    # run pyflakes
    - pyflakes . > pyflakeslog
    - if [[ $(wc -l < pyflakeslog) != 0 ]]; then echo "ERROR pyflakes failed!"; cat pyflakeslog; else echo "PASS pyflakes is happy!"; fi
    # run pylint --py3k (with some temporary exceptions)
    - pylint --py3k --score=no -d W1618,W1619,W1633,W1653 lmfdb/ > pylintlog
    - if [[ $(wc -l < pylintlog) != 0 ]]; then echo "ERROR pylint failed!"; cat pylintlog; else echo "PASS pylint is happy!"; fi
    # check that we travis isn't missing any test_ file
    - test $(find lmfdb -name 'test_*'  | wc -l) -eq 35
    # Check that pytest is installed
    - ${SAGE} -sh -c "pytest --version"
    # This runs without fail
    - ${SAGE} -sh -c "pytest --verbose -s --cov=lmfdb ${TESTFILE}"

after_failure:
    # what is the load on the server
    - uptime
    - if [[ $(wc -l < pyflakeslog) != 0 ]]; then echo "ERROR pyflakes failed!"; cat pyflakeslog; else echo "PASS pyflakes is happy!"; fi
    - if [[ $(wc -l < pylintlog) != 0 ]]; then echo "ERROR pylint failed!"; cat pylintlog; else echo "PASS pylint is happy!"; fi

after_success:
    # what is the load on the server
    - uptime
    #- COVERALLS_PARALLEL=true coveralls
    - coveralls
