language: sage
sudo: false
dist: trusty

addons:
    apt:
        packages:
            # needed for sage
            - binutils
            - gcc
            - g++
            - gfortran
            - make
            - perl
            - tar
            - git
            - openssl
            - libssl-dev
            # needed for pyflakes
            - python-pip
            # to have mongo shell
            - mongodb-org-shell
            # to run nosetests in parallel
            - parallel


install:
    # assert parallel
    - parallel --version
    # install the latest pyflakes
    - pip install pyflakes --user
    # install the latest coveralls
    - pip install coveralls --user
    - export PATH=${HOME}/.local/bin/:${PATH}
    # install SAGE with GAP already built in
    - export SAGE_VERSION=8.1
    - export SAGE_DIR=${HOME}/SageMath
    - export SAGE="${SAGE_DIR}/sage"
    - export SAGE_INSTALL_GCC=no
    - export MAKE='make -j4'
    - wget  --no-verbose https://storage.googleapis.com/sage-lmfdb/sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2
    # travis_wait extends the default 10 minute timeout to 30 minutes
    - travis_wait 30 time tar xf sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2 -C ${HOME}
    # trigger the patch once script
    - ${SAGE} --version > patch_once_log
    # assert that we have GAP
    - ${SAGE} -python -c 'from sage.all import gap;G = gap.TransitiveGroup(9, 2); print G'
    # install LMFDB requirements
    - ${SAGE} -pip install -r requirements.txt

before_script:
    # --cov-report= suppresses printing coverage to terminal
    - export COVERAGE='--cov=lmfdb --cov-report='
    # assert that m0.lmfdb.xyz accepts our connections
    - nc -vz  m0.lmfdb.xyz 27017
    # create a list of files and folder where we will run the tests
    - ls  lmfdb/*.py  > list
    - ls -d lmfdb/*/ >> list
    # how much free ram do we have
    - free -m
    # what is the load on the server
    - uptime

script:
    # run pyflakes
    - pyflakes lmfdb/ > pyflakeslog
    - if [[ $(wc -l < pyflakeslog) != 0 ]]; then echo "ERROR pyflakes failed!"; cat pyflakeslog; else echo "PASS pyflakes is happy!"; fi
    # run pytest in parallel with 3 jobs
    # usually we have at most 4gb of RAM per test, we should avoid running many jobs at once
    - ${SAGE} -python -m pytest -n 3 --verbosity=3 -s ${COVERAGE} | tee pytestlog

after_failure:
    - if [[ $(wc -l < pyflakeslog) != 0 ]]; then echo "ERROR pyflakes failed!"; cat pyflakeslog; else echo "PASS pyflakes is happy!"; fi
    # print the logs with failed tests
    - grep 'FAILED' -r pytestlog > greplog ; cat greplog

after_success:
    - ls -a
    - COVERALLS_PARALLEL=true coveralls
