name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout
      - name: autopep8
        uses: peter-evans/autopep8@v1
        if: ${{ github.repository }} == 'edgarcosta/lmfdb'
        with:
          # W291 - Remove trailing whitespace.
          # E303 - Remove extra blank lines.
          # E304 - Remove blank line following function decorator.
          # E722 - Fix bare except.
          # E252 - Missing whitespace around parameter equals.
          # E241 - Fix extraneous whitespace around keywords.
          # W602 - Fix deprecated form of raising exception.
          # E306 - Expected 1 blank line before a nested definition.
          # E714 - Use 'is not' test for object identity.
          # W690 - Fix various deprecated code (via lib2to3).
          # E301 - Add missing blank line.
          # E721 - Use "isinstance()" instead of comparing types directly.
          # W293 - Remove trailing whitespace on blank line.
          # E27 -  Fix extraneous whitespace around keywords.
          # W604 - Use "repr()" instead of backticks.
          # E401 - Put imports on separate lines.
          # W503 - Fix line break before binary operator.
          # W504 - Fix line break after binary operator.
          # E701 - Put colon-separated compound statement on separate lines.
          # E242 - Remove extraneous whitespace around operator.
          # W601 - Use "in" rather than "has_key()".
          # E251 - Remove whitespace around parameter '=' sign.
          # E712 - Fix comparison with boolean.
          # W292 - Add a single newline at the end of the file.
          # E26 -  Fix spacing after comment hash for inline comments.
          # W605 - Fix invalid escape sequence 'x'.
          # E711 - Fix comparison with None.
          # E502 - Remove extraneous escape of newline.
          # W603 - Use "!=" instead of "<>"
          # E70 -  Put semicolon-separated compound statement on separate lines.
          # E713 - Use 'not in' for test for membership.
          # W391 - Remove trailing blank lines.
          args: --recursive --in-place --aggressive --select=W291,E303,E304,E722,E252,E241,W602,E306,E714,W690,E301,E721,W293,E27,W604,E401,W503,W504,E701,E242,W601,E251,E712,W292,E26,W605,E711,E502,W603,E70,E713,W391 lmfdb/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: autopep8 action fixes
          title: Fixes by autopep8 action
          body: This is an auto-generated PR with fixes by autopep8.
          labels: autopep8, automated pr
          branch: autopep8-patches
