name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout
      - name: autopep8
        uses: peter-evans/autopep8@v1
        if: ${{ github.repository }} == 'edgarcosta/lmfdb'
        with:
          # E203 whitespace before ‘,’, ‘;’, or ‘:’
          # E222 multiple spaces after operator
          # E241 multiple spaces after ‘,’
          # E251 unexpected spaces around keyword / parameter equals
          # E301 expected 1 blank line, found 0
          # E302 expected 2 blank lines, found 0
          # E303 too many blank lines
          # E304 blank lines found after function decorator
          # E702 multiple statements on one line (semicolon)

          args: --recursive --in-place --aggressive --select=E203,E222,E241,E251,E301,E302,E303,E304,E702 lmfdb/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: autopep8 action fixes
          title: Fixes by autopep8 action
          body: This is an auto-generated PR with fixes by autopep8.
          labels: autopep8, automated pr
          branch: autopep8-patches
